# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-30 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180725_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Command'), (1, 'Python module'), (2, 'Docker Container'), (3, 'Smart docker module')], default=0),
        ),
    ]
