# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-02 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181002_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
