# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-09-11 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.Process'),
        ),
    ]
