# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-09-27 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190911_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
