# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-09-27 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_template_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
