# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-01-07 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190927_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Waiting'), (2, 'Running'), (3, 'Error'), (4, 'Done'), (5, 'Paused'), (6, 'Edited'), (7, 'Aborted')], default=0),
        ),
    ]
