# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-14 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200107_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Waiting'), (2, 'Running'), (3, 'Error'), (4, 'Done'), (5, 'Edited'), (6, 'Finished'), (7, 'Aborted')], default=0),
        ),
    ]
