# Generated by Django 2.2 on 2020-02-04 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200121_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='container_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='container_iteration',
        ),
        migrations.RemoveField(
            model_name='job',
            name='container_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='file_index',
        ),
        migrations.RemoveField(
            model_name='job',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='process',
            name='allFiles',
        ),
        migrations.AddField(
            model_name='module',
            name='parallell_jobs',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=1000)),
                ('status', models.IntegerField(choices=[(0, 'Not started'), (1, 'Started'), (2, 'Complete'), (3, 'Error')], default=0)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('iteration', models.IntegerField(default=1)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='api.Process')),
            ],
        ),
    ]
