# Generated by Django 2.2 on 2020-02-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200204_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.Process'),
        ),
    ]
