# always base every smart docker container on worker_base. 
#It contains all the logic for communicating the results
FROM worker_base

# for a simple command like ls we don't need to install anything
WORKDIR /
