# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-19 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.IntegerField(choices=[(0, 'Command'), (1, 'Python module'), (2, 'bash script')], default=0)),
                ('form', jsonfield.fields.JSONField(default=[])),
                ('python_module', models.CharField(max_length=100)),
                ('hidden', models.BooleanField(default=False)),
                ('command', jsonfield.fields.JSONField(default=[])),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('path', models.TextField()),
                ('file_name', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Waiting'), (2, 'Running'), (3, 'Error'), (4, 'Done'), (5, 'Edited')], default=0)),
                ('workdir', models.TextField()),
                ('logdir', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('process_id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=10000)),
                ('value', jsonfield.fields.JSONField(default={})),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Waiting'), (2, 'Running'), (3, 'Error'), (4, 'Done'), (5, 'Paused'), (6, 'Edited')], default=0)),
                ('log_path', models.CharField(blank=True, default='', max_length=100)),
                ('err_path', models.CharField(blank=True, default='', max_length=100)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='api.Module')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='api.Package')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
