# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-25 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(default=1, to='api.Role'),
        ),
    ]
