# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-19 12:24
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_process_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='statistics',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
