# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-20 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_package_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='hidden',
        ),
        migrations.AddField(
            model_name='module',
            name='multifile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process',
            name='fileList',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='module',
            name='python_module',
            field=models.CharField(default='', max_length=100),
        ),
    ]
