# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-30 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180930_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('container_id', models.CharField(blank=True, default='', max_length=100)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='api.Process')),
            ],
        ),
    ]
