# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-25 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180620_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='multifile',
        ),
        migrations.RemoveField(
            model_name='process',
            name='fileList',
        ),
        migrations.AddField(
            model_name='module',
            name='filter',
            field=models.CharField(default='*', max_length=200),
        ),
    ]
