# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-25 09:35
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180625_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='resultFilter',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
