# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-26 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='modules',
        ),
        migrations.AddField(
            model_name='process',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='api.Template'),
        ),
        migrations.AlterField(
            model_name='process',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='api.Package'),
        ),
    ]
