# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-27 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180626_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='active_template',
            field=models.TextField(default=''),
        ),
    ]
