# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-27 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_package_active_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='active_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='api.Template'),
        ),
    ]
