# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-28 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180627_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='id',
            new_name='template_id',
        ),
    ]
