# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-03 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdata',
            name='count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
