# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-03 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_filetype_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdata',
            name='date',
            field=models.DateField(),
        ),
    ]
