# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-05 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180703_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Waiting'), (2, 'Running'), (3, 'Error'), (4, 'Done'), (5, 'Edited'), (6, 'Finished')], default=0),
        ),
    ]
