# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-06 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20180705_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='command',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='module',
            name='form',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='module',
            name='resultFilter',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Command'), (1, 'Python module'), (2, 'bash script')], default=0),
        ),
    ]
