# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-11 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180706_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='docker',
            field=jsonfield.fields.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Command'), (1, 'Python module'), (2, 'Docker Container')], default=0),
        ),
    ]
