# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-11 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20180711_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='docker',
        ),
        migrations.AlterField(
            model_name='module',
            name='command',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
