# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-11 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180711_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='filter',
            field=models.CharField(blank=True, default='.*', max_length=200),
        ),
    ]
