# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-11 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20180711_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='docker',
            field=jsonfield.fields.JSONField(blank=True, default={'dockerfile': True, 'file_mount_point': '/file.pdf', 'image': '', 'workdir_mount_point': ''}),
        ),
        migrations.AddField(
            model_name='module',
            name='tool_folder_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
