# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-11 12:44
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180711_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='docker',
            field=jsonfield.fields.JSONField(blank=True, default='{"dockerfile":"1", "image": "", "workdir_mount_point": "", "file_mount_point": "/file.pdf"}'),
        ),
    ]
