# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-11 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20180711_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='docker',
        ),
    ]
