# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-13 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20180712_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='docker_mount_point',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
