# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-16 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_module_docker_mount_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerimage',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
