# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-18 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_dockerimage_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='description',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
