# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-19 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20180718_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='filter',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
